### ISSUE TITLE
Bug: Parameter not defined @ process_stepper.dart

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Flutter#10]
connectorThickness is not part of the parameters of the widget Stepper.

![imagen](https://github.com/ISIS3510-202320-Team13/Flutter/assets/60227071/f861b696-c5b8-4e48-b41a-84bca90cc42c)

![imagen](https://github.com/ISIS3510-202320-Team13/Flutter/assets/60227071/3e0de95b-d6df-4adb-8382-db2e89caad83)

**Comment by Crola1702** [comment]
Fixed in #13
