### ISSUE TITLE
Feat: Implement 3 Business Questions

### ISSUE THREAD

**Issue by Crola1702** [ISIS3510-202320-Team13/Flutter#15]
**Describe the feature we need to develop**
Implement 3 Business Questions from the Sprint 1 definition deliverable

- [x] [BQ1]
- [ ] [BQ2]
- [ ] [BQ3]

**Comment by JuanLugoS** [comment]
added notification card that let the user know if there is an upcoming or current reservation 
![imagen](https://github.com/ISIS3510-202320-Team13/Flutter/assets/60227071/42455a53-5149-4a2a-abf1-1297d7eeb6bc)
[0339725](https://github.com/ISIS3510-202320-Team13/Flutter/commit/0339725890e5f6c0e312e43c995bf21a0debe797)
