### ISSUE TITLE
Feat: Implement 1 caching strategy

### ISSUE THREAD

**Issue by Crola1702** [ISIS3510-202320-Team13/Flutter#18]
As the title says

> **Note**
> In the case that the functionalities of sprint 2 do not require this typeof strategies, you should implement a new functionality in your apps.

**Comment by JuanLugoS** [comment]
Removed the use of GPS in 'near_parkings.dart' by caching the latitude and longitude when accessed on the homepage. [08f4f7d](https://github.com/ISIS3510-202320-Team13/Flutter/commit/08f4f7d765cde22463c4ed134c0926fe29608464)
