### ISSUE TITLE
Interoperability issue: Modify reservation process to match the information

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Flutter#23]
Use the an async request to the back in order to retrieve the information of the specific parking
![imagen](https://github.com/ISIS3510-202320-Team13/Flutter/assets/60227071/1ecbf110-ea03-4a10-8feb-598d9e4a5f88)

**Comment by JuanLugoS** [comment]
the information required from a parking to do the reservation its the uid.
![imagen](https://github.com/ISIS3510-202320-Team13/Flutter/assets/60227071/a56a5dd5-0366-4597-bfe1-8daa7e03fc72)

**Comment by Crola1702** [comment]
Solved in #34
