### ISSUE TITLE
Bug: Haversine location display wrong information

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Flutter#44]
the distance to the parkings isn't the real distance

![Imagen de WhatsApp 2023-12-01 a las 18 56 28_87981664](https://github.com/ISIS3510-202320-Team13/Flutter/assets/60227071/837337ad-4efd-41a6-9a4d-2371ae92782b)

**Comment by Crola1702** [comment]
I think this is related to using `0.0, 0.0` as Latitude and Longitude :sweat_smile:. Probably an issue fetching the location.

However, I can't reproduce this problem. Can you explain how did you get these values? Are you still getting them?

**Comment by JuanLugoS** [comment]
Related to flutter version
