### ISSUE TITLE
Bug: bloc Enhance geolocation getting fatal error

### ISSUE THREAD

**Issue by JuanLugoS** [ISIS3510-202320-Team13/Flutter#45]
the app stops execution when going into the near parkings view, then back, then again into the view

![Imagen de WhatsApp 2023-12-01 a las 18 56 28_7942ae45](https://github.com/ISIS3510-202320-Team13/Flutter/assets/60227071/7053b448-d590-4848-a67f-c5a6fc091bbe)

**Comment by Crola1702** [comment]
Can you explain the steps you followed when you got this problem? I can't reproduce it on my phone :frowning_face:

**Comment by JuanLugoS** [comment]
Related to flutter version
